[package]
name = "day17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4.6.0"
image = { version = "0.24.7", features = [] }
imageproc = "0.23.0"
rusttype = "0.9.2"
